# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 347780fee3cd2cfe22772eef75e0f989c150b9ed8b396dded7c70eaa312469bfb0e997528fc675ebdf9c087ace8bf908c5bdcb68c2ed7c5353420e4ecdf20366

test:
  secret_key_base: 2fb5e9200d406270514fd122ccae740f8f3304fd8f5027c23a94075091bd2d41abf2d20f87616c6532e986fb3616395e4279bc758cbea561213e1998eb0900ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
